Exception on /server/uname/update/1 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 317, in server_uname_update
    app.Server.update(temp)
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 144, in update
    query_str = self.create_update_string(json_data)
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 246, in create_update_string
    query_str += "%s='%s', " % (self.columns[i], self.escape(json_data[self.columns[i]]))
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 256, in escape
    data_str = data.replace("'", "\\'")
AttributeError: 'ImmutableMultiDict' object has no attribute 'replace'
Exception on /server/uname/update/1 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 317, in server_uname_update
    app.Server.update(temp)
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 144, in update
    query_str = self.create_update_string(json_data)
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 246, in create_update_string
    query_str += "%s='%s', " % (self.columns[i], self.escape(json_data[self.columns[i]]))
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 256, in escape
    data_str = data.replace("'", "\\'")
AttributeError: 'ImmutableMultiDict' object has no attribute 'replace'
Exception on /server/uname/update/1 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 317, in server_uname_update
    app.Server.update(temp)
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 144, in update
    query_str = self.create_update_string(json_data)
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 246, in create_update_string
    query_str += "%s='%s', " % (self.columns[i], self.escape(json_data[self.columns[i]]))
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 256, in escape
    data_str = data.replace("'", "\\'")
AttributeError: 'ImmutableMultiDict' object has no attribute 'replace'
Exception on /server/uname/update/1 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 317, in server_uname_update
    app.Server.update(temp)
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 144, in update
    query_str = self.create_update_string(json_data)
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 246, in create_update_string
    query_str += "%s='%s', " % (self.columns[i], self.escape(json_data[self.columns[i]]))
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 256, in escape
    data_str = data.replace("'", "\\'")
AttributeError: 'ImmutableMultiDict' object has no attribute 'replace'
Exception on /server/uname/update/1 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 317, in server_uname_update
    app.Server.update(temp)
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 144, in update
    query_str = self.create_update_string(json_data)
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 246, in create_update_string
    query_str += "%s='%s', " % (self.columns[i], self.escape(json_data[self.columns[i]]))
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 256, in escape
    data_str = data.replace("'", "\\'")
AttributeError: 'dict' object has no attribute 'replace'
Exception on /server/uname/update/1 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 318, in server_uname_update
    app.Server.update(temp)
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 144, in update
    query_str = self.create_update_string(json_data)
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 246, in create_update_string
    query_str += "%s='%s', " % (self.columns[i], self.escape(json_data[self.columns[i]]))
  File "/Users/mcandres/sandbox/PACIFIC_NORTHSTAR/ssbautomator/models/baseModel.py", line 256, in escape
    data_str = data.replace("'", "\\'")
AttributeError: 'dict' object has no attribute 'replace'
Exception on /server/uname/update/1 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 318, in server_uname_update
    print tenp
NameError: global name 'tenp' is not defined
